retaildevcrews/ngsa-app

Controllers/ActorsController.cs
Controllers/FeaturedController.cs
Controllers/GenresController.cs
Controllers/MoviesController.cs
Controllers/ResultHandler.cs
Core/CommandLine.cs
Core/LogEventId.cs
Core/NgsaLog.cs
DataAccessLayer/dalMain.cs
DataAccessLayer/idal.cs
Program.cs
RequestLogger/RequestLogger.cs

merged logging changes from old repo

updated logging

---

DataAccessLayer/dalActors.cs
DataAccessLayer/dalMovies.cs
RequestLogger/RequestLogger.cs

- Prometheus updates per design review
- added CosmosName
- removed subcategory
- fixed cache bug

Prometheus updates

---

.github/workflows/ngsa.yaml

- added ci-cd to publish to ghcr.io
- Closes retaildevcrews/ngsa#497

added ci cd

---

docs/observability.md

Updates based on Observability and related Data Dictionary information.  
Closes [WCNP #108](https://github.com/retaildevcrews/wcnp/issues/108)

Added observability doc so that information may be found within the repo

---

Ngsa.App.csproj
src/Controllers/HealthzController.cs
src/Core/CommandLine.cs
src/Core/Config.cs
src/Core/PerfCounters.cs
src/HealthChecks/IetfResponseWriter.cs

- added X-Capacity-Metric header for bursting support
- added --burst-target and --burst-max command line / env var params
- uses CPU

Bursting Updates

---

src/Handlers/RequestLogger/RequestLogger.cs

- added CPU gauge to Prometheus /metrics endpoint
- Closes #32

added cpu to prometheus

---

README.md

This is an initial README structure and content for ngsa-app.
Closes: https://github.com/retaildevcrews/wcnp/issues/180

Abassey readme

---

.github/workflows/ngsa-pr.yaml

Separate file created to handle pull_request action
Closes: #[219](https://github.com/retaildevcrews/wcnp/issues/219)

Add PR Action to Validate Container Will Run for ngsa-app repo

---

.github/workflows/ngsa-pr.yaml

- Closes https://github.com/retaildevcrews/wcnp/issues/291

Update cosmos key to support upsert operations

---

.github/workflows/ngsa.yaml

References https://github.com/retaildevcrews/wcnp/issues/263

Updated ngsa workflow logic to run tests during schedule

---

README.md

Closes https://github.com/retaildevcrews/wcnp/issues/304

Add documentation for using burst metrics service option

---

src/Controllers/ActorsController.cs
src/Controllers/BenchmarkController.cs
src/Controllers/DataService.cs
src/Controllers/FeaturedController.cs
src/Controllers/GenresController.cs
src/Controllers/HealthzController.cs
src/Controllers/MoviesController.cs
src/Controllers/ResultHandler.cs
src/Core/BurstMetricsService.cs
src/Core/CommandLine.cs
src/Core/Config.cs
src/Core/NgsaLog.cs
src/Core/Secrets.cs
src/DataAccessLayer/InMemoryDal.cs
src/DataAccessLayer/Model/Actor.cs
src/DataAccessLayer/Model/Movie.cs
src/DataAccessLayer/QueryParameters/ActorQueryParameters.cs
src/DataAccessLayer/QueryParameters/MovieQueryParameters.cs
src/DataAccessLayer/dalMain.cs
src/DataAccessLayer/dalMovies.cs
src/Handlers/RequestLogger/RequestLogger.cs
src/Handlers/SwaggerExtension.cs
src/HealthChecks/CosmosHealthCheck.cs
src/HealthChecks/CosmosHealthCheckBuilderExtensions.cs
src/HealthChecks/CosmosHealthCheckDetails.cs
src/HealthChecks/IetfResponseWriter.cs
src/NgsaLogger/NgsaLogger.cs
src/NgsaLogger/NgsaLoggerExtensions.cs
src/NgsaLogger/NgsaLoggerProvider.cs
src/Program.cs

Closes https://github.com/retaildevcrews/wcnp/issues/306

Stylecop fixes

---

.github/workflows/ngsa-pr.yaml

References retaildevcrews/wcnp#293
Closes retaildevcrews/wcnp#293

Fixed bug for duplicate PR build

---

.github/workflows/ngsa.yaml
autogitops/autogitops.json
autogitops/ngsa-preprod.yaml

References: https://github.com/retaildevcrews/wcnp/issues/373

Added autogitops for ngsa-asb dev cluster

---

.github/workflows/ngsa.yaml
autogitops/autogitops.json
autogitops/ngsa-preprod.yaml

- To add central cluster for autogitops in ngsa-app.
- Added autogitops to workflow path
- Added some missing labels for autogitops
- References https://github.com/retaildevcrews/wcnp/issues/373

Added central preprod cluster and fixed minor bugs

---

.github/workflows/ngsa.yaml

References retaildevcrews/wcnp#401
Closes retaildevcrews/wcnp#401

Updated autogitops install to use version 0.0.3

---

.github/workflows/ngsa.yaml
autogitops/dev/ngsa-cosmos.yaml
autogitops/dev/ngsa-memory.yaml

- Fix implement autogitops for new dev clusters
- References https://github.com/retaildevcrews/wcnp/issues/568

Updated ago

---

autogitops/autogitops.json

To decomission old asb dev cluster reference for autogitops
- References https://github.com/retaildevcrews/wcnp/issues/568

Removed old asb dev cluster in autogitops config

---

autogitops/autogitops.json
autogitops/preprod/ngsa-cosmos.yaml
autogitops/preprod/ngsa-memory.yaml

update autogitops configs and template for new preprod envs

update autogitops configs and template for new preprod envs

---

autogitops/dev/ngsa-cosmos.yaml
autogitops/dev/ngsa-memory.yaml

References: https://github.com/retaildevcrews/wcnp/issues/621

Added readiness and liveness probes to dev clusters

---

autogitops/preprod/ngsa-cosmos.yaml
autogitops/preprod/ngsa-memory.yaml

References: https://github.com/retaildevcrews/wcnp/issues/621

Added liveness and readiness probes to preprod env

---

autogitops/autogitops.json

To remove target reference of old preprod cluster
- References https://github.com/retaildevcrews/wcnp/issues/620

Deleted old preprod cluster target

---

autogitops/dev/ngsa-memory.yaml

This should help with the AppEndpointDown alert.

Increase ngsa memory replicas, add rollingupdate

---

autogitops/dev/ngsa-cosmos.yaml
autogitops/dev/ngsa-memory.yaml

Add HPA spec in the ngsa deployment configs

Add HPA resource for ngsa in dev

---

Ngsa.App.csproj
README.md

To fix missing doc on how to launch codespace
Closes https://github.com/retaildevcrews/wcnp/issues/753

Updated README to include instructions to open with codespaces

---

README.md
autogitops/dev/ngsa-memory.yaml

- Documented restrictions for ngsa-memory template
- Updated ngsa-memory template by setting `replicas` to 1 and removed autoscaling
Closes: https://github.com/retaildevcrews/wcnp/issues/733

Updated README to include restrictions for ngsa-memory template

---

.github/workflows/ngsa.yaml

Change autogitops image from bartr/autogitops:beta to retaildevcrews/autogitops:0.3.0
- Closes https://github.com/retaildevcrews/wcnp/issues/777

Use retaildevcrews v0.3.0 image for autogitops

---

autogitops/dev/ngsa-cosmos.yaml
autogitops/preprod/ngsa-cosmos.yaml
autogitops/preprod/ngsa-memory.yaml

- Fix checkov yaml issues in ngsa cosmos and memory preprod deployment templates
- References https://github.com/retaildevcrews/wcnp/issues/637

Add Checkov linter fixes for preprod env

---

Ngsa.App.csproj

Update Nuget packages for LodeRunner projects 
- References https://github.com/retaildevcrews/wcnp/issues/805

Update NuGet packages

---

autogitops/autogitops.json

Testing NGSA namespace

---

autogitops/autogitops.json

Revert Testing NGSA namespace

---

.github/workflows/ngsa-pr.yaml
.github/workflows/ngsa.yaml

Update workflow to check if ngsa container stopped unexpectedly. If so, print the logs for a better debugging experience.
- References https://github.com/retaildevcrews/wcnp/issues/808

Show logs from detached container when it stops unexpectedly.

---

.github/workflows/ngsa-pr.yaml
.github/workflows/ngsa.yaml

- [] Code changes
Updated keys in github workflow to use test cosmos db. 
- Closes retaildevcrews/wcnp/issues/807
- Closes retaildevcrews/wcnp/issues/809

updated workflow secrets

---

.devcontainer/Dockerfile
.github/workflows/checkov-docker.yml
Dockerfile

Added Checkov action to CI/CD workflow to run on Dockerfiles
- Closes retaildevcrews/wcnp/issues/860

added dockerfile checkov, skip statements

---

.github/workflows/ngsa-pr.yaml
.github/workflows/ngsa.yaml

To add Grype vulnerability Scanner
- References https://github.com/retaildevcrews/wcnp/issues/905

Added Grype image vulnerability scanner

---

.github/workflows/ngsa-pr.yaml
.github/workflows/ngsa.yaml
src/Handlers/RequestLogger/RequestLogger.cs
src/NgsaLogger/NgsaLogger.cs

Log ParentSpanId in order to correlate order of tracing data from log analytics.
- References https://github.com/retaildevcrews/wcnp/issues/882

Add Parent Span ID

---

.vscode/tasks.json
src/NgsaLogger/NgsaLogger.cs

This is replicating the change made on the LodeRunner repo to address the task to log inner exceptions, since the NGSA Logger is part of this repo, propagated fix here
- Closes #121

log exception using ToString() instead of just the message property to ensure all details make it to logs

---

.github/workflows/ngsa-pr.yaml
.github/workflows/ngsa.yaml
Makefile
Ngsa.App.csproj

To fix the following vulnerabilities discovered in Grype:
- GHSA-cmhx-cq75-c4mj 
- GHSA-7jgj-8wvc-jh57
- GHSA-5crp-9r3c-p9vr
- Closes https://github.com/retaildevcrews/wcnp/issues/941

Fix vulnerabilities discovered in Grype

---

autogitops/dev/ngsa-cosmos.yaml

- increase app replicas from 1 to 2
- add the default deployment update strategy to the yaml for self-documentation
- this is already the default behavior, so no changes here
- References https://github.com/retaildevcrews/wcnp/issues/722

dev: Update app deployments for improved resiliency

---

autogitops/preprod/ngsa-cosmos.yaml

- increase app replicas from 1 to 2
- add the default deployment update strategy to the yaml for self documentation
- this is already the default behavior, so no changes here
- References https://github.com/retaildevcrews/wcnp/issues/722

preprod: Update app deployments for improved resiliency

---

autogitops/autogitops.json

This PR changes all name references in files and paths that refer to westus2 --> westus3 "West Us2" --> "West Us3", and centralus to northcentralus as well as "Central Us" --> "North Central Us".  This change is to reflect the current deployment regions.  
- Referenced https://github.com/retaildevcrews/wcnp/issues/1013

Update GitOps naming to reflect new regions 

---

autogitops/dev/ngsa-cosmos.yaml
autogitops/dev/ngsa-memory.yaml
autogitops/preprod/ngsa-cosmos.yaml
autogitops/preprod/ngsa-memory.yaml

- References https://github.com/retaildevcrews/wcnp/issues/1152

Update NodeSelector to use Node Type
